### ISSUE TITLE
Limit comment_history_delete.user.js to comment history pages only

### ISSUE THREAD

**Issue by mjpieters** [ArtOfCode-/Userscripts#1]
The comment_history_delete script is active on all pages on every site, but this causes issues in the flag review queue; each comment you delete from the flag queue triggers an error dialog with `Failed undefined: error`.

The `@match` URLs are overly broad and should just be limited to:

``` js
// @match       *://*.stackoverflow.com/admin/users/*/post-comments
// ... etc.
```

**Comment by ArtOfCode-** [comment]
Heh, good point. I thought that was done, but I copied the match block from another script of mine and replaced the old matches.
