### ISSUE TITLE
Script request: streamline creating a private room with a user

### ISSUE THREAD

**Issue by ArtOfCode-** [ArtOfCode-/Userscripts#3]
Mod tool. It should be easier to create a private room with a chat user. Add a link to their usercard to do that for you.

**Comment by samliew** [comment]
Something like this perhaps? :)

![](https://i.stack.imgur.com/F4L05.png)

### [CreatePrivateModChatroom](https://github.com/samliew/SO-mod-userscripts/blob/master/CreatePrivateModChatroom.user.js)

**Comment by ArtOfCode-** [comment]
Something exactly like that :)
