### ISSUE TITLE
Chat Profile broken link

### ISSUE THREAD

**Issue by DavidPostill** [ArtOfCode-/Userscripts#5]
Script is broken when running on SU.

Consider this user https://superuser.com/users/195700/nick:

Chat Profile link is https://chat.superuser.com/accounts/2323562 (broken link) 

It should be https://chat.stackexchange.com/accounts/2323562 (which then redirects correctly to https://chat.stackexchange.com/users/77598/nick)

**Comment by ArtOfCode-** [comment]
db281e94268463a818a79d3b6cde4a4d4d0a0e6d
