### ISSUE TITLE
Chat Profile link broken on FF.

### ISSUE THREAD

**Issue by DavidPostill** [ArtOfCode-/Userscripts#6]
Web sites prove their identity via certificates. Firefox does not trust this site because it uses a certificate that is not valid for chat.superuser.com. The certificate is only valid for the following names: chat.meta.stackexchange.com, chat.stackexchange.com, chat.stackoverflow.com, dev-bonfire.stackoverflow.com, dev-sockets.chat.stackexchange.com
 
Error code: SSL_ERROR_BAD_CERT_DOMAIN

when redirecting to for example https://chat.superuser.com/accounts/4230755

Is there a fix/workaround for this?

**Comment by ArtOfCode-** [comment]
the fix would be me writing code that's not stupid

**Comment by ArtOfCode-** [comment]
db281e94268463a818a79d3b6cde4a4d4d0a0e6d
